server:
  port: 8080


eureka:
# eureka服务的实例名
  instance:
    # 将服务以Ip的形式显示
    prefer-ip-address: true
  client:
    # 表示是否将当前服务注册到eureka
    register-with-eureka: false
    # fetch(抓取) 表示是否从eureka服务获取服务信息
    fetch-registry: true
    service-url:
      # eureka客户端注册或者发现服务的地址
      defaultZone: http://localhost:7961/eureka/



spring:
  application:
    name: springcloud-consumer

feign:
  hystrix:
    # 开启熔断
    enabled: true